"use client";

import { Check, ChevronDown, ChevronUp, HelpCircle, Minus, ShieldCheck, Sparkles, X } from "lucide-react";
import Link from "next/link";
import React, { useState } from "react";

export function FaqAndComparisonSection({ userOrgSlug }: { userOrgSlug?: string | null }) {
  const [openFaq, setOpenFaq] = useState<number | null>(0);

  const faqs = [
    {
      q: "How does OQVEN prevent AI code from breaking production?",
      a: "OQVEN enforces a strict multi-stage release gate. Code generated by AI is NEVER applied directly to production branches. It executes in an ephemeral, isolated Vercel Sandbox where automated allowlisted test suites (`npm test`, `typecheck`, `build`) must pass with 0 errors. Then a GitHub PR and Vercel Preview are created, requiring human approval before merging.",
    },
    {
      q: "Are my repository source code and secrets secure?",
      a: "Yes. All OpenHands repair artifacts that touch `.env`, PEM certificates, or private-key files are automatically blocked before persistence. Git credentials are removed from sandbox remotes immediately after clone/push operations, and data remains tenant-isolated via Supabase RBAC.",
    },
    {
      q: "Which AI models power OQVEN Copilot?",
      a: "OQVEN utilizes top-tier coding models routed through OpenRouter and OpenHands Cloud, including Claude 3.7 Sonnet, DeepSeek R1 / V3, and GPT-4o. Team plans can configure custom model routing or bring their own OpenRouter API keys.",
    },
    {
      q: "How does the interactive Copilot chat differ from standard IDE extensions?",
      a: "Standard IDE extensions only generate text snippets. OQVEN Copilot is an end-to-end autonomous engineering workspace: it reads your AST, searches cross-file dependencies, runs commands in an isolated Vercel Sandbox, executes tests, and delivers working pull requests.",
    },
    {
      q: "What payment and subscription methods are supported?",
      a: "We support major credit/debit cards, regional mobile transfers, and custom invoice billing for team and enterprise tiers. All subscriptions include immediate activation.",
    },
  ];

  const comparisonFeatures = [
    { feature: "Interactive Multi-Turn Copilot Chat", oqven: true, copilot: true, chatgpt: true },
    { feature: "Isolated Vercel Sandbox Execution", oqven: true, copilot: false, chatgpt: false },
    { feature: "Deterministic Test & Lint Gates (npm test)", oqven: true, copilot: false, chatgpt: false },
    { feature: "Autonomous Sentry Incident Ingestion", oqven: true, copilot: false, chatgpt: false },
    { feature: "Exact GitHub Merge SHA Observation", oqven: true, copilot: false, chatgpt: false },
    { feature: "Human-in-the-Loop PR Approval Gate", oqven: true, copilot: false, chatgpt: false },
    { feature: "Multi-Tenant RBAC & Audit Trails", oqven: true, copilot: false, chatgpt: false },
  ];

  return (
    <div className="space-y-24">
      {/* Comparison Table Section */}
      <section id="comparison" className="px-6 lg:px-12 max-w-6xl mx-auto">
        <div className="text-center max-w-3xl mx-auto mb-12">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-[#00E5FF]/10 border border-[#00E5FF]/30 text-[#00E5FF] text-xs font-mono mb-4">
            <ShieldCheck className="w-3.5 h-3.5" /> ARCHITECTURAL ADVANTAGE
          </div>
          <h2 className="text-3xl sm:text-4xl font-extrabold text-white tracking-tight">
            Why OQVEN vs Standard AI Tools
          </h2>
          <p className="mt-3 text-sm text-[#94A3B8]">
            Traditional AI outputs raw text. OQVEN runs, tests, and verifies working code in isolated containers.
          </p>
        </div>

        <div className="rounded-2xl border border-[#1E293B] bg-[#090D16] overflow-hidden shadow-xl">
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse text-xs font-mono">
              <thead>
                <tr className="border-b border-[#1E293B] bg-[#0B1018] text-[#94A3B8]">
                  <th className="p-4 sm:p-5 font-semibold text-white">Platform Capability</th>
                  <th className="p-4 sm:p-5 font-bold text-[#00E5FF] text-center bg-[#00E5FF]/5 border-x border-[#1E293B]">
                    OQVEN
                  </th>
                  <th className="p-4 sm:p-5 font-medium text-center">Standard Copilot</th>
                  <th className="p-4 sm:p-5 font-medium text-center">Raw ChatGPT</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-[#1E293B]/60 text-[#CBD5E1]">
                {comparisonFeatures.map((row, idx) => (
                  <tr key={idx} className="hover:bg-[#0B1018]/50 transition-colors">
                    <td className="p-4 sm:p-5 font-sans font-medium text-white">{row.feature}</td>
                    <td className="p-4 sm:p-5 text-center bg-[#00E5FF]/5 border-x border-[#1E293B]">
                      {row.oqven ? (
                        <div className="w-5 h-5 rounded-full bg-[#22C55E]/20 text-[#22C55E] flex items-center justify-center mx-auto">
                          <Check className="w-3.5 h-3.5" />
                        </div>
                      ) : (
                        <Minus className="w-4 h-4 text-[#64748B] mx-auto" />
                      )}
                    </td>
                    <td className="p-4 sm:p-5 text-center">
                      {row.copilot ? (
                        <Check className="w-4 h-4 text-[#94A3B8] mx-auto" />
                      ) : (
                        <X className="w-4 h-4 text-[#64748B] mx-auto" />
                      )}
                    </td>
                    <td className="p-4 sm:p-5 text-center">
                      {row.chatgpt ? (
                        <Check className="w-4 h-4 text-[#94A3B8] mx-auto" />
                      ) : (
                        <X className="w-4 h-4 text-[#64748B] mx-auto" />
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </section>

      {/* FAQ Section */}
      <section id="faq" className="px-6 lg:px-12 max-w-4xl mx-auto">
        <div className="text-center mb-12">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-[#00E5FF]/10 border border-[#00E5FF]/30 text-[#00E5FF] text-xs font-mono mb-4">
            <HelpCircle className="w-3.5 h-3.5" /> FREQUENTLY ASKED QUESTIONS
          </div>
          <h2 className="text-3xl sm:text-4xl font-extrabold text-white tracking-tight">
            Developer Questions & Answers
          </h2>
          <p className="mt-3 text-sm text-[#94A3B8]">
            Everything you need to know about OQVEN execution safety, pricing, and infrastructure.
          </p>
        </div>

        <div className="space-y-4">
          {faqs.map((faq, idx) => {
            const isOpen = openFaq === idx;
            return (
              <div
                key={idx}
                className="rounded-xl border border-[#1E293B] bg-[#090D16] overflow-hidden transition-all"
              >
                <button
                  type="button"
                  onClick={() => setOpenFaq(isOpen ? null : idx)}
                  className="w-full p-5 text-left flex items-center justify-between gap-4 hover:bg-[#0B1018] transition-colors"
                >
                  <span className="font-semibold text-sm sm:text-base text-white">{faq.q}</span>
                  {isOpen ? (
                    <ChevronUp className="w-4 h-4 text-[#00E5FF] shrink-0" />
                  ) : (
                    <ChevronDown className="w-4 h-4 text-[#64748B] shrink-0" />
                  )}
                </button>
                {isOpen && (
                  <div className="px-5 pb-5 pt-1 text-xs sm:text-sm text-[#94A3B8] leading-relaxed border-t border-[#1E293B]/40">
                    {faq.a}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </section>

      {/* High-Converting Closing Banner */}
      <section className="px-6 lg:px-12 max-w-6xl mx-auto pb-8">
        <div className="rounded-3xl border border-[#00E5FF]/30 bg-gradient-to-b from-[#0B1018] to-[#070A10] p-8 sm:p-14 text-center relative overflow-hidden shadow-[0_0_48px_rgba(0,229,255,0.15)]">
          <div className="absolute top-0 right-0 w-80 h-80 bg-[#00E5FF]/10 rounded-full blur-3xl pointer-events-none -mr-20 -mt-20" />
          <div className="relative z-10 max-w-2xl mx-auto space-y-6">
            <h2 className="text-3xl sm:text-5xl font-black text-white tracking-tight">
              Ready to automate your engineering pipeline?
            </h2>
            <p className="text-sm sm:text-base text-[#94A3B8]">
              Give it a task. Get working, deterministic code in an isolated Vercel Sandbox. Launch your first workspace in 30 seconds.
            </p>
            <div className="pt-2 flex flex-col sm:flex-row items-center justify-center gap-4">
              <Link
                href={userOrgSlug ? `/${userOrgSlug}/workspaces` : "/onboarding"}
                className="w-full sm:w-auto bg-[#00E5FF] text-[#00363D] hover:bg-[#00E5FF]/90 font-bold text-sm px-8 py-4 rounded-xl shadow-[0_0_24px_rgba(0,229,255,0.35)] transition-all hover:scale-102 flex items-center justify-center gap-2"
              >
                <Sparkles className="w-4 h-4" />
                Launch Free Workspace
              </Link>
              <Link
                href="/login"
                className="w-full sm:w-auto bg-[#090D16] border border-[#1E293B] hover:border-white/30 text-white text-sm px-6 py-4 rounded-xl transition-all"
              >
                Sign In to Dashboard
              </Link>
            </div>
            <div className="text-[11px] font-mono text-[#64748B] pt-2">
              Free 10 repairs included &bull; No credit card required &bull; Instant setup
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
